[tool.poetry]
name = "pyletsdoit-team"
version = "0.1.0"
description = ""
authors = ["Elena Vorobyeva <elvorob@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
selenium = "^4.5.0"
black = "^22.10.0"
flake8 = "^5.0.4"
pytest = "^7.2.0"
webdriver-manager = "^3.8.4"
