name: GitHub Actions Saucedemo
on: [push, pull_request]
jobs:
Explore-GitHub-Actions:
runs-on: ubuntu-latest
steps:
  - name: Checkout this repo
    uses: actions/checkout@v3
  - name: Setup python
    uses: actions/setup-python@v4
    with:
      python-version: '3.10'
  - name: Check code for errors by flake8 and format code with black
    uses: ricardochaves/python-lint@v1.4.0
    with:
      python-root-list: ""
      use-pylint: false
      use-pycodestyle: false
      use-flake8: true
      use-black: true
      use-mypy: false
      use-isort: false
      extra-pylint-options: ""
      extra-pycodestyle-options: ""
      extra-flake8-options: "--count --benchmark --ignore=E501,F401,W503"
      extra-black-options: ". -S"
      extra-mypy-options: ""
      extra-isort-options: ""
  - name: Update repo
    run: sudo apt-get update
  - name: Install Chrome
    uses: browser-actions/setup-chrome@latest
  - name: Install Firefox
    uses: riccione/setup_firefox@v1
  - name: Check Chromium version
    run: chromium-browser --version
  - name: Install poetry
    uses: snok/install-poetry@v1
    with:
      virtualenvs-create: true
      virtualenvs-in-project: true
      installer-parallel: true
  - name: Load cached venv
    id: cached-poetry-dependencies
    uses: actions/cache@v3
    with:
      path: .venv
      key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
  - name: Install dependencies
    if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
    run: poetry install --no-interaction --no-root
  - name: Run pytest
    run: poetry run pytest